/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current principal, effective role, and impersonation state */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/impersonation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Begin impersonating a role (SUPER_ADMIN only; all actions still audited as Super Admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ImpersonationRequest"];
                };
            };
            responses: {
                /** @description Impersonation active */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        /** Stop impersonating */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Stopped */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List applications (role-scoped; owners see their own) */
        get: {
            parameters: {
                query?: {
                    /** @description Opaque pagination cursor */
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                    status?: components["schemas"]["OnboardingStatus"];
                    owner?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApplicationPage"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * Create an onboarding request (DRAFT)
         * @description Idempotent via Idempotency-Key (replay → original 201). 409 here means a genuine business conflict (e.g. duplicate application name), NOT an idempotency replay. 422 = same key, different body.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Client-generated key. Replay (same key) → original response, never a duplicate side effect. Same key + different body → 422. Scope: per-principal + per-endpoint; retained 24h. A genuine business conflict (e.g. duplicate name) is a 409, not an idempotency replay. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ApplicationCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        ETag: components["headers"]["ETag"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Application"];
                    };
                };
                /** @description Business conflict (e.g. duplicate name) — not an idempotency replay */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                422: components["responses"]["Unprocessable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        ETag: components["headers"]["ETag"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Application"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a DRAFT/CHANGES_REQUESTED application (optimistic concurrency) */
        patch: {
            parameters: {
                query?: never;
                header: {
                    /** @description ETag from a prior GET; rejects the write with 412 if the resource changed. */
                    "If-Match": components["parameters"]["IfMatch"];
                };
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ApplicationPatch"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        ETag: components["headers"]["ETag"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Application"];
                    };
                };
                412: components["responses"]["PreconditionFailed"];
            };
        };
        trace?: never;
    };
    "/applications/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit (DRAFT → SUBMITTED) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Client-generated key. Replay (same key) → original response, never a duplicate side effect. Same key + different body → 422. Scope: per-principal + per-endpoint; retained 24h. A genuine business conflict (e.g. duplicate name) is a 409, not an idempotency replay. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                    /** @description ETag from a prior GET; rejects the write with 412 if the resource changed. */
                    "If-Match": components["parameters"]["IfMatch"];
                };
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Submitted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Application"];
                    };
                };
                409: components["responses"]["Conflict"];
                412: components["responses"]["PreconditionFailed"];
                422: components["responses"]["Unprocessable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approver decision (APPROVE | REJECT | REQUEST_CHANGES). Separation of duties — requester != approver (real principal, even while impersonating). */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Client-generated key. Replay (same key) → original response, never a duplicate side effect. Same key + different body → 422. Scope: per-principal + per-endpoint; retained 24h. A genuine business conflict (e.g. duplicate name) is a 409, not an idempotency replay. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                    /** @description ETag from a prior GET; rejects the write with 412 if the resource changed. */
                    "If-Match": components["parameters"]["IfMatch"];
                };
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DecisionBody"];
                };
            };
            responses: {
                /** @description Decision applied */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Application"];
                    };
                };
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
                412: components["responses"]["PreconditionFailed"];
                422: components["responses"]["Unprocessable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TimelineEntry"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    type?: components["schemas"]["ResourceType"];
                    risk?: components["schemas"]["Risk"];
                    /** @description Opaque pagination cursor */
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CatalogPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CatalogResource"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/access-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["AccessStatus"];
                    type?: components["schemas"]["AccessRequestKind"];
                    /** @description Opaque pagination cursor */
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccessRequestPage"];
                    };
                };
            };
        };
        put?: never;
        /** Create an access request (SUBMITTED) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Client-generated key. Replay (same key) → original response, never a duplicate side effect. Same key + different body → 422. Scope: per-principal + per-endpoint; retained 24h. A genuine business conflict (e.g. duplicate name) is a 409, not an idempotency replay. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AccessRequestCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccessRequest"];
                    };
                };
                409: components["responses"]["Conflict"];
                422: components["responses"]["Unprocessable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/access-requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccessRequest"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/access-requests/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approver decision. Separation of duties enforced on the real principal (even while impersonating). */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Client-generated key. Replay (same key) → original response, never a duplicate side effect. Same key + different body → 422. Scope: per-principal + per-endpoint; retained 24h. A genuine business conflict (e.g. duplicate name) is a 409, not an idempotency replay. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                    /** @description ETag from a prior GET; rejects the write with 412 if the resource changed. */
                    "If-Match": components["parameters"]["IfMatch"];
                };
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DecisionBody"];
                };
            };
            responses: {
                /** @description Decision applied */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccessRequest"];
                    };
                };
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
                412: components["responses"]["PreconditionFailed"];
                422: components["responses"]["Unprocessable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/my-access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MyAccessItem"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/my-access/{resourceId}/removal": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resourceId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request removal of a granted resource (creates an access-request kind=removal) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Client-generated key. Replay (same key) → original response, never a duplicate side effect. Same key + different body → 422. Scope: per-principal + per-endpoint; retained 24h. A genuine business conflict (e.g. duplicate name) is a 409, not an idempotency replay. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    resourceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removal request created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccessRequest"];
                    };
                };
                422: components["responses"]["Unprocessable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unified queue of items UNDER_REVIEW across both request types */
        get: {
            parameters: {
                query?: {
                    type?: "onboarding" | "access";
                    /** @description Opaque pagination cursor */
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewQueuePage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Team"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Client-generated key. Replay (same key) → original response, never a duplicate side effect. Same key + different body → 422. Scope: per-principal + per-endpoint; retained 24h. A genuine business conflict (e.g. duplicate name) is a 409, not an idempotency replay. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TeamCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Team"];
                    };
                };
                422: components["responses"]["Unprocessable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamMember"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Client-generated key. Replay (same key) → original response, never a duplicate side effect. Same key + different body → 422. Scope: per-principal + per-endpoint; retained 24h. A genuine business conflict (e.g. duplicate name) is a 409, not an idempotency replay. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TeamMemberAdd"];
                };
            };
            responses: {
                /** @description Added */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamMember"];
                    };
                };
                422: components["responses"]["Unprocessable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{id}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                userId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Soft-delete a member (audited) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query the hash-chained audit log */
        get: {
            parameters: {
                query?: {
                    actor?: string;
                    type?: string;
                    resource?: string;
                    from?: string;
                    to?: string;
                    /** @description Opaque pagination cursor */
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditPage"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify the audit hash chain is intact (single-writer append; tamper-evident) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditVerifyResult"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    /** @description Opaque pagination cursor */
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotificationFeed"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Marked read */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All marked read */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistant/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Wizard assistant (STUBBED in v1 core; full RAG/tools in a later track) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Client-generated key. Replay (same key) → original response, never a duplicate side effect. Same key + different body → 422. Scope: per-principal + per-endpoint; retained 24h. A genuine business conflict (e.g. duplicate name) is a 409, not an idempotency replay. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssistantChatRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssistantChatResponse"];
                    };
                };
                422: components["responses"]["Unprocessable"];
                /** @description Not implemented (assistant track deferred) */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistant/actions/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a proposed AI write-action (human-in-the-loop). STUBBED in v1 core. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not implemented */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Role: "APPLICATION_OWNER" | "SSO_OPERATIONS" | "ADMIN" | "AUDITOR" | "READ_ONLY" | "SUPER_ADMIN";
        /** @enum {string} */
        OnboardingStatus: "DRAFT" | "SUBMITTED" | "UNDER_REVIEW" | "CHANGES_REQUESTED" | "REJECTED" | "APPROVED" | "PROVISIONING" | "ACTIVE";
        /** @enum {string} */
        AccessStatus: "SUBMITTED" | "UNDER_REVIEW" | "CHANGES_REQUESTED" | "REJECTED" | "APPROVED" | "PROVISIONING" | "GRANTED";
        /** @enum {string} */
        Decision: "APPROVE" | "REJECT" | "REQUEST_CHANGES";
        /** @enum {string} */
        ResourceType: "AWS" | "WORKDAY" | "ROLE" | "TEAM";
        /** @enum {string} */
        Risk: "LOW" | "MEDIUM" | "HIGH";
        /** @enum {string} */
        AccessRequestKind: "grant" | "removal";
        /** @enum {string} */
        GrantType: "authorization_code" | "client_credentials" | "implicit" | "device_code";
        Problem: {
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
            instance?: string;
            correlationId?: string;
        };
        Me: {
            id?: string;
            name?: string;
            email?: string;
            /** @description Display role only (most-privileged of the held app roles). NOT the basis for authorization — the server checks permissions as the union of all assigned roles. */
            role?: components["schemas"]["Role"];
            /** @description All app roles held by the principal (the `roles` claim); authorization is the union of these. */
            roles?: components["schemas"]["Role"][];
            /** @description Informational access-governance/team group; NOT the RBAC source */
            group?: string | null;
            isSuperAdmin?: boolean;
            impersonating?: {
                role?: components["schemas"]["Role"];
            } | null;
        };
        /** @description v1 ships role-level impersonation (set `role`). The optional `user` is reserved for future user-level impersonation so adding it later is not a contract change; ignored in v1. */
        ImpersonationRequest: {
            role: components["schemas"]["Role"];
            /** @description Reserved (future user-level impersonation); ignored in v1 */
            user?: string | null;
        };
        Application: {
            id?: string;
            name?: string;
            /** @example dev */
            env?: string;
            description?: string;
            status?: components["schemas"]["OnboardingStatus"];
            owner?: string;
            team?: string[];
            grants?: components["schemas"]["GrantType"][];
            scopes?: string[];
            redirectUris?: string[];
            group?: string;
            /** @description Set after provisioning */
            clientId?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ApplicationCreate: {
            name: string;
            env: string;
            description?: string;
            grants?: components["schemas"]["GrantType"][];
            scopes?: string[];
            uris?: string[];
            group?: string;
            team?: string[];
        };
        ApplicationPatch: {
            description?: string;
            grants?: components["schemas"]["GrantType"][];
            scopes?: string[];
            uris?: string[];
            group?: string;
            team?: string[];
        };
        DecisionBody: {
            decision: components["schemas"]["Decision"];
            reason?: string;
        };
        TimelineEntry: {
            id?: string;
            status?: string;
            actor?: string;
            reason?: string | null;
            /** Format: date-time */
            at?: string;
        };
        CatalogResource: {
            id?: string;
            name?: string;
            type?: components["schemas"]["ResourceType"];
            risk?: components["schemas"]["Risk"];
            description?: string;
            /** @description Entra group an approval grants membership to */
            mappedGroup?: string;
        };
        AccessRequest: {
            id?: string;
            resourceId?: string;
            resourceName?: string;
            kind?: components["schemas"]["AccessRequestKind"];
            status?: components["schemas"]["AccessStatus"];
            requester?: string;
            justification?: string;
            /** @description ISO-8601 duration or null for permanent */
            duration?: string | null;
            approver?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        AccessRequestCreate: {
            resourceId: string;
            justification: string;
            duration?: string | null;
        };
        MyAccessItem: {
            resourceId?: string;
            resourceName?: string;
            /** Format: date-time */
            grantedAt?: string;
            requestId?: string;
        };
        Team: {
            id?: string;
            name?: string;
            description?: string;
            memberCount?: number;
        };
        TeamCreate: {
            name: string;
            description?: string;
        };
        TeamMember: {
            userId?: string;
            name?: string;
            /** Format: date-time */
            addedAt?: string;
        };
        TeamMemberAdd: {
            userId: string;
        };
        ReviewItem: {
            id?: string;
            /** @enum {string} */
            kind?: "onboarding" | "access";
            title?: string;
            requester?: string;
            /** Format: date-time */
            submittedAt?: string;
        };
        AuditEvent: {
            id?: string;
            /** Format: int64 */
            seq?: number;
            /** @description Identity (Super Admin even while impersonating) */
            actor?: string;
            effectiveRole?: components["schemas"]["Role"];
            action?: string;
            resourceType?: string;
            resourceId?: string;
            /** Format: date-time */
            at?: string;
            prevHash?: string;
            hash?: string;
            detail?: {
                [key: string]: unknown;
            };
        };
        AuditVerifyResult: {
            valid?: boolean;
            /**
             * Format: int64
             * @description Highest seq verified
             */
            checkedThrough?: number;
            /**
             * Format: int64
             * @description First seq where the chain breaks, or null
             */
            brokenAt?: number | null;
        };
        Notification: {
            id?: string;
            type?: string;
            title?: string;
            body?: string;
            resourceRef?: string | null;
            read?: boolean;
            /** Format: date-time */
            createdAt?: string;
        };
        NotificationFeed: {
            items?: components["schemas"]["Notification"][];
            unreadCount?: number;
            nextCursor?: string | null;
        };
        AssistantChatRequest: {
            message: string;
            /** @description Wizard fields in progress */
            context?: {
                [key: string]: unknown;
            };
        };
        AssistantChatResponse: {
            reply?: string;
            proposedActions?: components["schemas"]["ProposedAction"][];
        };
        ProposedAction: {
            id?: string;
            /** @enum {string} */
            tool?: "draftDescription" | "validateRedirectUris" | "recommendScopes" | "checkGroupOwnership";
            args?: {
                [key: string]: unknown;
            };
            requiresApproval?: boolean;
        };
        ApplicationPage: {
            items?: components["schemas"]["Application"][];
            nextCursor?: string | null;
        };
        CatalogPage: {
            items?: components["schemas"]["CatalogResource"][];
            nextCursor?: string | null;
        };
        AccessRequestPage: {
            items?: components["schemas"]["AccessRequest"][];
            nextCursor?: string | null;
        };
        ReviewQueuePage: {
            items?: components["schemas"]["ReviewItem"][];
            nextCursor?: string | null;
        };
        AuditPage: {
            items?: components["schemas"]["AuditEvent"][];
            nextCursor?: string | null;
        };
    };
    responses: {
        /** @description No/invalid session */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Insufficient permission / SoD / ownership */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description State or idempotency conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description ETag mismatch */
        PreconditionFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Validation error */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        Id: string;
        /** @description Opaque pagination cursor */
        Cursor: string;
        Limit: number;
        /** @description Client-generated key. Replay (same key) → original response, never a duplicate side effect. Same key + different body → 422. Scope: per-principal + per-endpoint; retained 24h. A genuine business conflict (e.g. duplicate name) is a 409, not an idempotency replay. */
        IdempotencyKey: string;
        /** @description ETag from a prior GET; rejects the write with 412 if the resource changed. */
        IfMatch: string;
    };
    requestBodies: never;
    headers: {
        /** @description Opaque version token for optimistic concurrency */
        ETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
